### ISSUE TITLE
pandas version 

### ISSUE THREAD

**Issue by px172** [AIforGreatGood/biotransfer#5]
Thanks for sharing the codes and pre-trained model. The environment.yaml file does not indicate the version of pandas. In my case, Conda installed version 2.0.3, which caused demo 2 to fail due to the deprecation of frame.append in pandas 2.0. The solution is to downgrade pandas to version 1.x. Demo 2 was successfully executed when I downgraded pandas to version 1.5.3.

**Comment by wjk1214** [comment]
src/explores/explorer.py line 220 modify
	sequences_data = sequences_data.append(
	sequences_data = sequences_data._append(
